apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: openclaw-config

labels:
  - pairs:
      app: openclaw
      managedBy: argocd
      managementCodeGroup: chrismlee42
      managementCodeProject: openclaw-config

namespace: openclaw

resources:
  - namespace.yaml