apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: openclaw
  name: openclaw
data:
  openclaw.json: |
    {
      "agents": {
        "defaults": {
          "imageModel": {
            "primary": "openrouter/anthropic/claude-opus-4-6"
          },
          "model": {
            "primary": "anthropic/claude-opus-4-6",
            "fallbacks": [
              "anthropic/claude-sonnet-4-5"
            ]
          },
          "models": {
            "anthropic/claude-opus-4-6": {
              "alias": "opus"
            },
            "anthropic/claude-sonnet-4-5": {
              "alias": "sonnet"
            }
          },
          "workspace": "~/.openclaw/workspace",
          "userTimezone": "America/Chicago"
        }
      },
      "channels": {
        "discord": {,
          "allowFrom": [
            "LabMonkey42",
            "labmonkey42"
          ]
          "dm": {
            "enabled": true
          },
          "enabled": true
        }
      },
      "tools": {
        "exec": {
          "ask": "off",
          "security": "full"
        }
      }
    }