apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: openclaw
  name: openclaw
data:
  openclaw.json: |
    {
      agent: {
        workspace: "~/.openclaw/workspace",
      },
      agents: {
        defaults: {
          imageModel: {
            primary: "openrouter/anthropic/claude-opus-4-6",
          },
          model: {
            primary: "anthropic/claude-opus-4-6",
            fallbacks: ["anthropic/claude-sonnet-4-5", "openai/gpt-5.2"],
          },
          models: {
            "anthropic/claude-opus-4-6": { alias: "opus" },
            "anthropic/claude-sonnet-4-5": { alias: "sonnet" },
            "openai/gpt-5.2": { alias: "gpt" },
          },
          userTimezone: "America/Chicago",
        },
      },
      channels: {
        discord: {
          dm: {
            enabled: true,
            allowFrom: [
              "LabMonkey42"
            ]
          },
          enabled: true,
        },
      },
      identity: {
        name: "Dot",
        theme: "helpful sloth",
        emoji: "ðŸ¦¥",
      },
    }